version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "prueba"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m4a0n69qiss0"
s3_prefix = "prueba"
region = "us-east-1"
profile = "sahily-cli"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
